const page = document.body.dataset.page || '';
const navItems = [['Home','index.html','home'],['About Us','about.html','about'],['Products','products.html','products'],['Services','services.html','services'],['Sectors','clients.html','clients'],['Contact','contact.html','contact']];
const header = document.querySelector('[data-site-header]');
if (header) { header.innerHTML = `<div class="topline"><span>Trance Towers, Tsavo Road</span><span>020-221 1956</span><span>info@activepowerltd.co.ke</span></div><header class="site-header"><a class="logo" href="index.html"><img src="assets/logo.png" alt="Active Power Energy Limited" class="brand-mark logo-only"><span class="brand-name">Active Power<br>Energy Limited</span></a><button class="menu-button" aria-label="Open navigation"><span></span><span></span><span></span></button><nav class="nav">${navItems.map(([label,href,key])=>`<a class="${page===key?'active':''}" href="${href}">${label}</a>`).join('')}<a class="header-cta" href="contact.html">Get a Quote <b>→</b></a></nav></header>`; header.querySelector('.menu-button').addEventListener('click',()=>header.querySelector('.nav').classList.toggle('open')); }
const footer = document.querySelector('[data-site-footer]');
if (footer) { footer.innerHTML = `<footer class="site-footer"><div class="footer-grid"><div class="footer-brand"><a class="logo footer-logo" href="index.html"><img src="assets/logo.png" alt="Active Power Energy Limited" class="brand-mark logo-only"><span>Stand-by Power Solutions across East Africa.</span></a></div><div class="footer-col"><h4>Quick Links</h4><div class="footer-links"><span><a href="index.html">Home</a><a href="about.html">About Us</a><a href="products.html">Products</a></span><span><a href="services.html">Services</a><a href="clients.html">Sectors</a><a href="contact.html">Contact</a></span></div></div><div class="footer-col"><h4>Contact</h4><span class="footer-contact">Trance Towers, Tsavo Road</span><a href="tel:0202211956">020-221 1956</a><a href="mailto:info@activepowerltd.co.ke">info@activepowerltd.co.ke</a></div></div><div class="footer-bottom"><span>© 2026 Active Power Energy Limited</span><span>Stand-by Power Solutions across East Africa</span></div></footer>`; }
const serviceData={support:['01 / ALWAYS HERE','24/7 technical support.','Our technical team is available around the clock to help keep your power system operating reliably.',['24/7 technical assistance','Responsive troubleshooting','Support across East Africa']],maintenance:['02 / PROTECT YOUR EQUIPMENT','Planned maintenance.','Scheduled maintenance helps protect performance, extend equipment life and reduce unplanned downtime.',['Scheduled service visits','Preventive system checks','Performance recommendations']],spares:['03 / GENUINE PARTS','The right spare parts.','We supply genuine spare parts to help maintain the reliability and quality of your equipment.',['Genuine parts','Quality components','Parts guidance']],projects:['04 / BUILT AROUND YOUR NEEDS','Tailor-made power projects.','We configure integrated power solutions around your site, load and operating requirements.',['Site and load assessment','Equipment configuration','Installation and commissioning']],skip:['05 / LOCATE WHAT MATTERS','Find the missing link.','Skip tracing helps locate debtors who have moved or are avoiding their obligations. Michex supports businesses that need a clearer route to the person of interest.',['Debtor location support','People and address tracing','Debt-focused investigations','Clear next steps']],receivables:['06 / PROTECT YOUR CASH FLOW','Make every invoice count.','Our accounts receivable management service helps customers pay within agreed credit terms and strengthens a company’s liquidity position.',['Reconciliations','Statement dispatch','Payment negotiations','In-house training and monthly reports']],business:['07 / SET UP WITH CLARITY','Build the right foundation.','We support company, partnership, sole proprietor and cooperative registrations, changes of structure and directors, annual returns and business proposals.',['Business registration','Annual returns','Business plans','Funding and project proposals']],management:['08 / SEE THE BIGGER PICTURE','Better performance starts here.','Our management consulting services give organisations access to experienced, objective advice and specialised expertise.',['Objective advice','Specialised expertise','Performance improvement','Experienced consultants']],agents:['09 / ENTER THE MARKET','A local route to opportunity.','We represent local, regional and international clients testing products and services in the Kenyan market through a network of warehousing, sales outlets and social networks.',['Market entry support','Commission-based representation','Sales outlet network','Reduced setup costs']]};
function showService(key){const data=serviceData[key],detail=document.querySelector('.service-detail');if(!data||!detail)return;detail.innerHTML=`<span class="service-index">${data[0]}</span><h2>${data[1]}</h2><p>${data[2]}</p><div class="service-points">${data[3].map(item=>`<span>${item}</span>`).join('')}</div>`;document.querySelectorAll('.service-tab').forEach(tab=>tab.classList.toggle('active',tab.dataset.service===key));}
document.querySelectorAll('.service-tab').forEach(tab=>tab.addEventListener('click',()=>{showService(tab.dataset.service);history.replaceState(null,'',`#${tab.dataset.service}`);}));
if(document.querySelector('.service-detail')){
  const requestedService = (new URLSearchParams(window.location.search)).get('service') || window.location.hash.replace('#','') || 'support';
  showService(serviceData[requestedService] ? requestedService : 'support');
  if (window.location.hash && document.querySelector(`.service-tab[data-service="${window.location.hash.replace('#','')}"]`)) {
    document.querySelector(`.service-tab[data-service="${window.location.hash.replace('#','')}"]`).scrollIntoView({block:'nearest',behavior:'smooth'});
  }
}
const partnerLogos=[['assets/nakilogo.png','NAKI logo'],['assets/metropol.png','Metropol Credit Reference Bureau logo'],['assets/Equity_Bank_Logo.png','Equity Bank logo'],['assets/coperativebanklogo.webp','Co-operative Bank logo'],['assets/SAF-MAIN-LOGO.png','Safaricom / M-Pesa logo'],['assets/etims.png','eTIMS logo']];
const partnerTrack=document.querySelector('.trust-grid article:first-child .logos');
if(partnerTrack){partnerTrack.innerHTML=`<div class="partner-track">${partnerLogos.concat(partnerLogos).map(([src,alt])=>`<span class="partner-logo"><img src="${src}" alt="${alt}"></span>`).join('')}</div>`;}
const bankerTrack=document.querySelector('.trust-grid article:nth-child(2) .logos');
if(bankerTrack){const bankerLogos=[['assets/Equity_Bank_Logo.png','Equity Bank logo'],['assets/coperativebanklogo.webp','Co-operative Bank logo']];bankerTrack.innerHTML=`<div class="partner-track">${bankerLogos.concat(bankerLogos).map(([src,alt])=>`<span class="partner-logo"><img src="${src}" alt="${alt}"></span>`).join('')}</div>`;}
const clientTrack=document.querySelector('.trust-grid article:nth-child(4) .logos');
if(clientTrack){const clientLogos=[['assets/surgipharmlogo.png','Surgipharm logo'],['assets/rostrumlogo.jpg','Rostrum logo'],['assets/Reckitt-logo.jpg','Reckitt logo'],['assets/eldohosplogo.png','Eldoret Hospital logo'],['assets/HighChem-East-Africa-Logo-W.png','HighChem East Africa logo'],['assets/powergovernorslogo.jpg','Power Governors logo'],['assets/usn_kenya___ultimate_sports_nutrition_logo.jpg','USN Kenya logo'],['assets/kingswaylogo.jpg','Kingsway logo']];clientTrack.innerHTML=`<div class="partner-track">${clientLogos.concat(clientLogos).map(([src,alt])=>`<span class="partner-logo"><img src="${src}" alt="${alt}"></span>`).join('')}</div>`;}



